# Generated by Django 4.0.5 on 2022-08-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_alter_artifact_material'),
        ('archive', '0018_alter_starbucksmug_date'),
    ]

    operations = [
    ]
