# Generated by Django 4.0.5 on 2022-08-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_merge_20220805_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starbucksmug',
            old_name='subject',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='starbucksmug',
            old_name='sizeOunces',
            new_name='capacityInOunces',
        ),
        migrations.RenameField(
            model_name='starbucksmug',
            old_name='displayedLocation',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='starbucksmug',
            old_name='productionLocation',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='starbucksmug',
            name='date',
        ),
        migrations.RemoveField(
            model_name='starbucksmug',
            name='link3DModel',
        ),
        migrations.RemoveField(
            model_name='starbucksmug',
            name='productLink',
        ),
        migrations.RemoveField(
            model_name='starbucksmug',
            name='text',
        ),
        migrations.AddField(
            model_name='starbucksmug',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='starbucksmug',
            name='shapeDescription',
            field=models.TextField(blank=True),
        ),
    ]
